### ISSUE TITLE
Is the VST model optimised separately for each dataset to obtained the results in the paper?

### ISSUE THREAD

**Issue by Pager07** [tim-roderick/VST#3]
Meaning did you end up with 1 unique set of weights and hyper-parameters for each dataset in the set {Summe, Tvsum, Summe_Aug, Tvsum_Aug}?

**Comment by Pager07** [comment]
@tim-roderick , is that is like a yes?

**Comment by tim-roderick** [comment]
Sorry, that was a yes 👍
